### ISSUE TITLE
analyzer styleguide

### ISSUE THREAD

**Issue by kalle202** [rts-cmk-wu08/hifi-corner-sandkage#11]
- [x] find ud hvor de forskellige farver bliver brugt, evt fordel dem til de forskellige komponenter

- [x] analyzer hvilke tykkelser og størrelser der skal bruges på de forskellige tekster på siden

kompleksitet: 6

**Comment by SebCodiing** [comment]
- Header: 
background-color: #000000


- Buttons: 
background-color: #FF6900
color: #F4F4F2 og
 #495464

icons:
color: #FFFFFF

- Nav links: #FFFFFF
p text skal i header og footer være med farvekode: #FFFFFF
p text skal i section midt på siden være med farvekode: #000000;
p text skal på payment page være med farvekode: #495464

tekst boxen på compare skal være med farvekoden: #C4C4C4;

På About Us siden skal der være en subtitle med farvekoden: #FF6900

- Søgefelt:
Background color: ##495464
Font color: #F4F4F2;

Hover:
Background color: ##495464
Font color: #F4F4F2
box-shadow: 4px 4px 4px rgba(0, 0, 0, 0.25);
